wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclo"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search/", views.search, name="search" ),
    path("new/", views.new_page, name= "new_page"),
    path("edit/", views.edit, name= "edit"),
    path("save_edit/", views.save_edit, name= "save_edit"),
    path("rand/", views.rand, name= "rand"),


]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
import markdown
from . import util
import random


def convert_md_to_html(title):
    content = util.get_entry(title)
    markdowner = markdown.Markdown()
    if content == None:
        return None
    else:
         return markdowner.convert(content)


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    html_content= convert_md_to_html(title)
    if html_content == None:
        return render(request, "encyclopedia/error.html", {
            "message": "This entry does not exist"
        })
    else:
        return render (request, "encyclopedia/entry.html",{
            "title" : title,
            "content" : html_content
        } )

def search (request):
    if request.method == "POST":
        entry_search = request.POST ['s']
        html_content = convert_md_to_html (entry_search) 
        if html_content is not None:
            return render (request, "encyclopedia/entry.html",{
                "title" : entry_search,
                "content" : html_content
            })
        else:
            allEntries = util.list_entries()
            suggestion = []
            for entry in allEntries:
                if entry_search.lower() in entry.lower():
                    suggestion.append(entry)
            return render(request, "encyclopedia/search.html", {
                "suggestion" : suggestion
            })    

def new_page(request):
    if request.method== "GET":
        return render(request, "encyclopedia/new.html")
    else:
        title = request.POST ['title']
        content = request.POST ['content']
        titleExist = util.get_entry(title)
        if titleExist is not None:
            return render (request, "encyclopedia/error.html", {
                "message" : "Entry page already exists"
            })
        else: 
            util.save_entry(title, content)
            html_content = convert_md_to_html(title,)
            return render(request, "encyclopedia/entry.html", {
                "title": title, 
                "content": html_content
            })
   
def edit (request):
    if request.method == 'POST':
       title = request.POST ['entry_title']
       content = util.get_entry(title)
       return render (request, "encyclopedia/edit.html", {
           "title" : title,
           "content" : content
       } )

def save_edit (request):
    if request.method == "POST":
        title = request.POST ['title']
        content = request.POST ['content']
        util.save_entry(title, content)
        html_content = convert_md_to_html (title) 
        return render (request, "encyclopedia/entry.html",{
            "title" : title,
            "content" : html_content
        })
    
def rand(request):
    allEntries = util.list_entries ()
    rand_entry = random.choice (allEntries)
    html_content = convert_md_to_html (rand_entry)
    return render(request, "encyclopedia/entry.html",{
        "title" : rand_entry,
        "content" : html_content

    })

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>New Page </h1>

    <br/>

    <form action="{% url 'encyclo:save_edit' %}" method="POST">
        {% csrf_token %}
        <label> New Title:</label>
        <input type="text" name="title" placeholder="Title" value=" {{ title }} " >
        <br/>
        <label> New Content:</label>
        <br/>
        <textarea name= "content" >{{ content }} </textarea>
        <br/>
        <input type="submit" value= "Confirm Changes" class=" btn btn-primary">
    </form> 

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title | safe }}
{% endblock %}

{% block body %}
    {{ content | safe }}

    <form action="{% url 'encyclo:edit' %} " method= "POST">
        {% csrf_token %}
        <input type="hidden" name = "entry_title" value ="{{ title }}">
        <input type= "submit" value = "Edit" class = "btn btn-danger"> 
    </form>


{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Error </h1>

    <h2> {{ message }}</h2>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href = "{% url 'encyclo:entry' title=entry %}" >{{ entry }} </a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclo:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="s" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclo:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclo:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclo:rand' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>New Page </h1>

    <br/>

    <form action="{% url 'encyclo:new_page' %}" method="POST">
        {% csrf_token %}
        <label> New Title:</label>
        <input type="text" name="title" placeholder="Title">
        <br/>
        <label> New Content:</label>
        <br/>
        <textarea name= "content"placeholder="Content"></textarea>
        <br/>
        <input type="submit" value= "New Page" class=" btn btn-primary">
    </form> 

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search</h1>

    <ul>
        {% for entry in suggestion %}
            <li> <a href = "{% url 'encyclo:entry' title=entry %}" >{{ entry }} </a></li>
        {% endfor %}
    </ul>

{% endblock %}